<a href="https://colab.research.google.com/github/ZAHID188/Q-learning_collab/blob/main/Q_learning_Beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q-Learning lesson





Define the Q-table: The Q-table is a matrix that represents the Q-values for each state-action pair. In this example, we initialize a Q-table with zeros.

In [ ]:
import numpy as np

# Define the Q-table
num_states = 5
num_actions = 3
Q = np.zeros((num_states, num_actions)) #make a row-5, column-3 array   Creating a 2-dimensional array
print(Q)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Define the rewards matrix: The rewards matrix defines the rewards for each state-action pair. In this example, we use a 5x3 matrix where -1 represents a negative reward and 100 represents a positive reward for reaching the goal state.

The value 0 in the last row indicates that no reward is given for taking an action in the goal state.

In [ ]:
# Define the rewards matrix
rewards = np.array([
    [-1, -1, -1],
    [-1, -1, -1],
    [-1, -1, -1],
    [-1, -1, -1],
    [0, -1, 100]])
print(rewards)


[[ -1  -1  -1]
 [ -1  -1  -1]
 [ -1  -1  -1]
 [ -1  -1  -1]
 [  0  -1 100]]


Define the discount factor: The discount factor (gamma) determines the importance of future rewards compared to immediate rewards. In this example, we set gamma to 0.8.

Define the learning rate: The learning rate determines the impact of new information on the Q-values. In this example, we set the learning rate to 0.5.


Define the number of episodes: An episode represents a complete run-through of the Q-learning algorithm. In this example, we set the number of episodes to 1000.

In [ ]:
# Define the discount factor
gamma = 0.8

# Define the learning rate
learning_rate = 0.5

# Define the number of episodes
num_episodes = 1000





1. Q-learning algorithm: The Q-learning algorithm consists of multiple episodes, where the agent learns to update the Q-values based on the rewards received.
    
    a. Initialize the state: At the start of each episode, we randomly select an initial state.
    
    ```python
    state = np.random.randint(0, num_states)
    
    ```
    
    b. Perform Q-learning until the goal state is reached:
    
    i. Choose an action: The agent selects an action based on the highest Q-value for the current state.
    
    ```python
    action = np.argmax(Q[state])
    
    ```
    
    ii. Transition to the next state: The agent transitions to the next state by randomly selecting one.
    
    ```python
    next_state = np.random.randint(0, num_states)
    
    ```
    
    iii. Get the reward: The agent receives a reward based on the current state-action pair.
    
    ```python
    reward = rewards[state, action]
    
    ```
    
    iv. Update the Q-value: The Q-value for the current state-action pair is updated using the Q-learning equation.
    
    ```python
    Q[state, action] += learning_rate * (reward + gamma * np.max(Q[next_state]) - Q[state, action])
    
    ```
    
    v. Move to the next state: The agent moves to the next state.
    
    ```python
    state = next_state
    
    ```
    
    vi. Check if the goal state is reached: If the agent reaches the goal state, the episode ends.
    
    ```python
    if state == num_states - 1:
        done = True
    
    ```


## np.argmax
```
import numpy as np

# Create a 1-dimensional array
arr = np.array([2, 5, 1, 8, 4])

# Find the index of the maximum value in the array
max_index = np.argmax(arr)

print(max_index)
# Output: 3
```



# Q-learning algorithm

In [ ]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = np.random.randint(0, num_states)  # Initial state
    done = False

    while not done:
        action = np.argmax(Q[state])  # Choose action with highest Q-value

        next_state = np.random.randint(0, num_states)  # Randomly select next state
        reward = rewards[state, action]  # Get reward for current state-action pair

        Q[state, action] += learning_rate * (reward + gamma * np.max(Q[next_state]) - Q[state, action])

        state = next_state  # Move to next state

        if state == num_states - 1:
            done = True



In [ ]:
# Testing the learned policy
state = 0  # Initial state

while state != num_states - 1:
    action = np.argmax(Q[state])  # Choose action with highest Q-value

    print("Current state:", state)
    print("Action:", action)

    state = np.random.randint(0, num_states)  # Randomly select next state

print("Reached the goal stat!e!")

Current state: 0
Action: 0
Current state: 2
Action: 0
Current state: 3
Action: 1
Current state: 2
Action: 0
Current state: 1
Action: 0
Current state: 0
Action: 0
Current state: 2
Action: 0
Reached the goal stat!e!


#snake game

In [4]:
import pygame
import random
import numpy as np

# Constants
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600
BLOCK_SIZE = 20
GAME_SPEED = 100  # Higher value means slower game

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)

# Q-learning parameters
EPSILON = 0.9  # Exploration rate
ALPHA = 0.1  # Learning rate
GAMMA = 0.6  # Discount factor
EPISODES = 25000  # Number of games to train

# Initialize PyGame
pygame.init()
font = pygame.font.Font(None, 25)
clock = pygame.time.Clock()

# Q-table
q_table = {}

# Helper functions
def get_state(head, food):
    """
    Get the current state of the game.
    """
    x1, y1 = head.x, head.y
    x2, y2 = food.x, food.y
    return (x1 - x2, y1 - y2)

def get_next_action(state, epsilon):
    """
    Get the next action to take based on the current state and epsilon value.
    """
    if random.random() < epsilon:
        return random.randint(0, 3)  # Explore
    else:
        values = q_table.get(state, [0, 0, 0, 0])
        return np.argmax(values)  # Exploit

def update_q_table(state, action, reward, next_state):
    """
    Update the Q-table based on the current state, action, reward, and next state.
    """
    q_value = q_table.get(state, [0, 0, 0, 0])
    next_q_value = q_table.get(next_state, [0, 0, 0, 0])
    max_next_q_value = max(next_q_value)
    q_value[action] += ALPHA * (reward + GAMMA * max_next_q_value - q_value[action])
    q_table[state] = q_value

# Snake class
class Snake:
    def __init__(self):
        self.x = WINDOW_WIDTH // 2
        self.y = WINDOW_HEIGHT // 2
        self.body = [(self.x, self.y)]
        self.direction = 0  # 0: up, 1: right, 2: down, 3: left

    def move(self, action):
        """
        Move the snake based on the given action.
        """
        x = self.body[0][0]
        y = self.body[0][1]
        if action == 0:
            y -= BLOCK_SIZE  # Up
        elif action == 1:
            x += BLOCK_SIZE  # Right
        elif action == 2:
            y += BLOCK_SIZE  # Down
        else:
            x -= BLOCK_SIZE  # Left

        self.body.insert(0, (x, y))
        self.body.pop()

    def draw(self, surface):
        """
        Draw the snake on the game surface.
        """
        for x, y in self.body:
            pygame.draw.rect(surface, GREEN, (x, y, BLOCK_SIZE, BLOCK_SIZE))

# Food class
class Food:
    def __init__(self):
        self.x = random.randint(0, WINDOW_WIDTH - BLOCK_SIZE) // BLOCK_SIZE * BLOCK_SIZE
        self.y = random.randint(0, WINDOW_HEIGHT - BLOCK_SIZE) // BLOCK_SIZE * BLOCK_SIZE

    def draw(self, surface):
        """
        Draw the food on the game surface.
        """
        pygame.draw.rect(surface, RED, (self.x, self.y, BLOCK_SIZE, BLOCK_SIZE))

# Game loop
def play_game(display):
    snake = Snake()
    food = Food()
    score = 0
    game_over = False

    while not game_over:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                game_over = True

        state = get_state(snake.body[0], food)
        action = get_next_action(state, EPSILON)
        snake.move(action)

        # Check if the snake has eaten the food
        if snake.body[0][0] == food.x and snake.body[0][1] == food.y:
            score += 1
            food = Food()
            snake.body.append(snake.body[-1])
            reward = 1
        else:
            reward = 0

        # Check if the snake has collided with itself or the boundary
        x, y = snake.body[0]
        if x < 0 or x >= WINDOW_WIDTH or y < 0 or y >= WINDOW_HEIGHT or (x, y) in snake.body[1:]:
            game_over = True
            reward = -1

        next_state = get_state(snake.body[0], food)
        update_q_table(state, action, reward, next_state)

        display.fill(BLACK)
        snake.draw(display)
        food.draw(display)
        score_text = font.render(f"Score: {score}", True, WHITE)
        display.blit(score_text, (10, 10))
        pygame.display.update()
        clock.tick(GAME_SPEED)

    return score

# Training loop
def train():
    display = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))
    pygame.display.set_caption("Snake Game")

    max_score = 0
    for episode in range(EPISODES):
        score = play_game(display)
        if score > max_score:
            max_score = score
        print(f"Episode: {episode + 1}, Score: {score}, Max Score: {max_score}")

    pygame.quit()

# Start training
train()

AttributeError: 'tuple' object has no attribute 'x'

Here's how the code works:

*   The Snake class represents the snake in the game. It has a body (a list of coordinates), a direction, and methods to move and draw the snake.
*   The Food class represents the food in the game. It has random coordinates and a method to draw the food.
The play_game function is the main game loop. It initializes the snake, food, and score, and then iterates through the game loop until the game is over.
*   In each iteration of the game loop, the current state is obtained using the get_state function, which calculates the relative position of the snake's head and the food.
*   The next action is determined using the get_next_action function, which either explores (random action) or exploits (action with the highest Q-value) based on the epsilon value.
*   The snake moves according to the chosen action.
*   If the snake eats the food, the score is incremented, a new food is generated, and the snake's body grows. A positive reward is given.
*   If the snake collides with itself or the boundary, the game is over, and a negative reward is given.
*   The Q-table is updated using the update_q_table function, which calculates the new Q-value based on the current state, action, reward, and next state.
*   The game is rendered using PyGame, and the score is displayed.
*   The train function is the main entry point. It creates a PyGame window, runs the training loop for a specified number of episodes, and keeps track of the maximum score achieved.

During training, the snake learns to play the game by updating the Q-table based on the rewards it receives. After training, the snake should be able to play the game effectively by exploiting the learned Q-values.

Note that this implementation doesn't include any visualization of the training process or the ability to play the game after training. You can modify the code to add these features if desired.