<a href="https://colab.research.google.com/github/ZAHID188/Q-learning_collab/blob/main/Q_learning_Beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q-Learning lesson





Define the Q-table: The Q-table is a matrix that represents the Q-values for each state-action pair. In this example, we initialize a Q-table with zeros.

In [5]:
import numpy as np

# Define the Q-table
num_states = 5
num_actions = 3
Q = np.zeros((num_states, num_actions)) #make a row-5, column-3 array   Creating a 2-dimensional array
print(Q)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Define the rewards matrix: The rewards matrix defines the rewards for each state-action pair. In this example, we use a 5x3 matrix where -1 represents a negative reward and 100 represents a positive reward for reaching the goal state.

The value 0 in the last row indicates that no reward is given for taking an action in the goal state.

In [4]:
# Define the rewards matrix
rewards = np.array([
    [-1, -1, -1],
    [-1, -1, -1],
    [-1, -1, -1],
    [-1, -1, -1],
    [0, -1, 100]])
print(rewards)


[[ -1  -1  -1]
 [ -1  -1  -1]
 [ -1  -1  -1]
 [ -1  -1  -1]
 [  0  -1 100]]


Define the discount factor: The discount factor (gamma) determines the importance of future rewards compared to immediate rewards. In this example, we set gamma to 0.8.

Define the learning rate: The learning rate determines the impact of new information on the Q-values. In this example, we set the learning rate to 0.5.


Define the number of episodes: An episode represents a complete run-through of the Q-learning algorithm. In this example, we set the number of episodes to 1000.

In [ ]:
# Define the discount factor
gamma = 0.8

# Define the learning rate
learning_rate = 0.5

# Define the number of episodes
num_episodes = 1000





1. Q-learning algorithm: The Q-learning algorithm consists of multiple episodes, where the agent learns to update the Q-values based on the rewards received.
    
    a. Initialize the state: At the start of each episode, we randomly select an initial state.
    
    ```python
    state = np.random.randint(0, num_states)
    
    ```
    
    b. Perform Q-learning until the goal state is reached:
    
    i. Choose an action: The agent selects an action based on the highest Q-value for the current state.
    
    ```python
    action = np.argmax(Q[state])
    
    ```
    
    ii. Transition to the next state: The agent transitions to the next state by randomly selecting one.
    
    ```python
    next_state = np.random.randint(0, num_states)
    
    ```
    
    iii. Get the reward: The agent receives a reward based on the current state-action pair.
    
    ```python
    reward = rewards[state, action]
    
    ```
    
    iv. Update the Q-value: The Q-value for the current state-action pair is updated using the Q-learning equation.
    
    ```python
    Q[state, action] += learning_rate * (reward + gamma * np.max(Q[next_state]) - Q[state, action])
    
    ```
    
    v. Move to the next state: The agent moves to the next state.
    
    ```python
    state = next_state
    
    ```
    
    vi. Check if the goal state is reached: If the agent reaches the goal state, the episode ends.
    
    ```python
    if state == num_states - 1:
        done = True
    
    ```


## np.argmax
```
import numpy as np

# Create a 1-dimensional array
arr = np.array([2, 5, 1, 8, 4])

# Find the index of the maximum value in the array
max_index = np.argmax(arr)

print(max_index)
# Output: 3
```



# Q-learning algorithm

In [14]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = np.random.randint(0, num_states)  # Initial state
    done = False

    while not done:
        action = np.argmax(Q[state])  # Choose action with highest Q-value

        next_state = np.random.randint(0, num_states)  # Randomly select next state
        reward = rewards[state, action]  # Get reward for current state-action pair

        Q[state, action] += learning_rate * (reward + gamma * np.max(Q[next_state]) - Q[state, action])

        state = next_state  # Move to next state

        if state == num_states - 1:
            done = True



In [15]:
# Testing the learned policy
state = 0  # Initial state

while state != num_states - 1:
    action = np.argmax(Q[state])  # Choose action with highest Q-value

    print("Current state:", state)
    print("Action:", action)

    state = np.random.randint(0, num_states)  # Randomly select next state

print("Reached the goal stat!e!")

Current state: 0
Action: 0
Current state: 2
Action: 0
Current state: 3
Action: 1
Current state: 2
Action: 0
Current state: 1
Action: 0
Current state: 0
Action: 0
Current state: 2
Action: 0
Reached the goal stat!e!
